[webServer]
HTTPSAddr = ":8443"
HTTPAddr  = ":8081"
CA        = "./cert/CA.pem"
Key       = "./cert/ss.key"
Cert      = "./cert/ss.crt"
DisableHttp = "false"
DisableHttps = "false"

[aaa]
PolicyModelPath = "authModel.conf"
PolicyFilePath = "authPolicy.csv"
Auditing = "true"
AuditingLogAddress = "/tmp/audit.log"
Bypass = "false"